name: cromalink

services:
  cromolink-db:
    build:
      context: ./mysql-db
    container_name: cromalink_db

    # restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "acr321"
      TZ: America/Montevideo
    volumes:
      - ./cromalink-db.sql:/docker-entrypoint-initdb.d/start.sql
      - cromalink-db-volume:/var/lib/mysql


volumes:
  cromalink-db-volume: {}
  