name: cromalink

services:
  cromolink_db:
    build:
      context: ./mysql-db
    container_name: cromalink_db
    hostname: cromalink_db
    networks:
      - cromalink
    # restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Cr0m4l1nK.root"
      MYSQL_DATABASE: "cromalink_db"
      MYSQL_USER: "cromalink_user"
      MYSQL_PASSWORD: "Cr0m4l1nK."
      TZ: America/Montevideo
    volumes:
      - cromalink_db_volume:/var/lib/mysql

volumes:
  cromalink_db_volume: {}

networks:
  cromalink:
    name: cromalink
    driver: bridge
  

