name: cromalink

services:
  cromolink-db:
    image: mysql:lts
    container_name: cromalink-db
    
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "acr321"
      # MYSQL_DATABASE: cromalink-db
      # MYSQL_USER: cromalink-user
      # MYSQL_PASSWORD: Cr0m4l1nK.
      TZ: America/Montevideo
    volumes:
      - cromalink-db-volume:/var/lib/mysql


volumes:
  cromalink-db-volume: {}
  